VSS:
  name: Valda's Spire of Secrets

TGS:
  name: The Griffon's Saddlebag

tgs1:
  name: The Griffon's Saddlebag - Book 1

KibblesTasty:CC:
  name: KibblesTasty's Casting Compendium

CUSTOM:
  name: Personalizzato

KTKCG:
  name: KibblesTasty's Crafting Guide

EsploratoriNebbia:
  name: Personalizzato (Esploratori della Nebbia)